wandb_version: 1

lr:
  desc: null
  value: 0.0001
num_epochs:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700154775.294874
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
