script = "vae_trainer.py" # not used for now
path_dataset_train = "/var/hub/datasets/zalando-hd-resized/train/image"
path_dataset_test = "/var/hub/datasets/zalando-hd-resized/test/image"
path_dataset_val = "/var/hub/datasets/zalando-hd-resized/val/image"

[wandb]
mode = "online"  # online : enregistrer le test sur wandb, offline : ne pas enregistrer le test sur wandb
entity = "finegrain-cs"
project = "vton_details_preservation"
name = "vae_256_latent_dim_1e-5_KR"    

[models]
vae = {train = true}#{checkpoint="/home/daniel/work/vton/notebooks/autoencodeur_models/test.safetensors", train=true}

[training]
duration = "30:epoch"
seed = 42
gpu_index = 0
num_epochs = 30
batch_size = 1
gradient_accumulation = "1:step"
evaluation_interval = "1:epoch"
evaluation_seed = 42
anealer = "linear" # "linear" , "cosine" , "logistic" , "none" 

[optimizer]
optimizer = "Adam" # "AdamW", "AdamW8bit", "Lion8bit", "Prodigy", "SGD", "Adam"
learning_rate = 1e-5


[scheduler]
scheduler_type = "ConstantLR"
update_interval = "1:step"

[dropout]
dropout_probability = 0.1


[dataset]
# on a besoin de le laisser à cause du model BaseConfig

[checkpointing]
save_folder = "models"
save_interval = "1:epoch"

