script = "autoencodeur_trainer.py" # not used for now
path_dataset_train = "datasets/data_cats_vs_dogs/data_train"
path_dataset_test = "datasets/data_cats_vs_dogs/data_test"
path_dataset_val = "datasets/data_cats_vs_dogs/data_val"

[wandb]
mode = "offline"  # online : enregistrer le test sur wandb, offline : ne pas enregistrer le test sur wandb
entity = "finegrain-cs"
project = "cats"
name = "test_trainer_refiners_2"

[models]
autoencoder = {train = true}#{checkpoint="/home/daniel/work/vton/notebooks/autoencodeur_models/test.safetensors", train=true}

[training]
duration = "3:epoch"
seed = 42
gpu_index = 0
num_epochs = 3
batch_size = 1
gradient_accumulation = "1:step"
evaluation_interval = "1:epoch"
evaluation_seed = 42


[optimizer]
optimizer = "Adam" # "AdamW", "AdamW8bit", "Lion8bit", "Prodigy", "SGD", "Adam"
learning_rate = 1e-4


[scheduler]
scheduler_type = "ConstantLR"
update_interval = "1:step"

[dropout]
dropout_probability = 0.1


[dataset]
# on a besoin de le laisser à cause du model BaseConfig

[checkpointing]
# save_folder = "/path/to/ckpts"
save_interval = "1:epoch"

